version: '3.9'

services:
  web:
    build: .
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/code

    environment:
      - SECRET_KEY=test
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - SECURE_SSL_REDIRECT=False
      - SECURE_HSTS_SECONDS=0
      - SECURE_HSTS_INCULDE_SUBDOMAINS=False
      - SECURE_HSTS_PRELOAD=False
      - SESSION_COOKIE_SECURE=False
      - CSRF_COOKIE_SECURE=False
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

volumes:
  postgres_data: