# Generated by Django 4.0.10 on 2023-07-05 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_options_alter_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 14, 43, 20, 464589, tzinfo=utc)),
        ),
    ]
