# Generated by Django 4.0.10 on 2023-07-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_published_date_book_id_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
